name: Run check lint & run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v23
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm install --include=dev --frozen-lockfile --non-interactive

      - name: Check code formatting
        run: npm run lint

      - name: Run tests
        run: npm run test